apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-app
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: k8s-test-app
  template:
    metadata:
      labels:
        app: k8s-test-app
    spec:
      containers:
      - name: k8s-test-app
        image: k8s-test-app:latest
        imagePullPolicy: Never  # Tell Kubernetes not to pull from a registry
        # image: vikash95/kubernetes-test-app:latest # if pulling from cloud.
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service # service.yaml to configure same port for every node in the cluster.
metadata:
  name: k8s-test-app
spec:
  selector:
    app: k8s-test-app
  ports:
  - port: 5000
    targetPort: 5000